### ISSUE TITLE
Multiple newlines cause fails

### ISSUE THREAD

**Issue by mgraauw** [proycon/babelente#12]
Hi,

I also get an error if a file contains multiple consecutive newlines:
Traceback (most recent call last):
  File "C:\Programs\Python36\Scripts\babelente-script.py", line 11, in <module>
    load_entry_point('BabelEnte==0.4.0', 'console_scripts', 'babelente')()
  File "C:\Programs\Python36\lib\site-packages\babelente-0.4.0-py3.6.egg\babelente\babelente.py", line 514, in main
    sourceentities = [ entity for  entity in findentities(sourcelines, args.sourcelang, args, None if cache is None else cache['source']) if entity['isEntity'] and 'babelSynsetID' in entity ] #with sanity check
  File "C:\Programs\Python36\lib\site-packages\babelente-0.4.0-py3.6.egg\babelente\babelente.py", line 514, in <listcomp>
    sourceentities = [ entity for  entity in findentities(sourcelines, args.sourcelang, args, None if cache is None else cache['source']) if entity['isEntity'] and 'babelSynsetID' in entity ] #with sanity check
  File "C:\Programs\Python36\lib\site-packages\babelente-0.4.0-py3.6.egg\babelente\babelente.py", line 126, in findentities
    raise e
  File "C:\Programs\Python36\lib\site-packages\babelente-0.4.0-py3.6.egg\babelente\babelente.py", line 119, in findentities
    entity['linenr'], entity['offset'] = resolveoffset(offsetmap, entity['start'], lines, entity)
  File "C:\Programs\Python36\lib\site-packages\babelente-0.4.0-py3.6.egg\babelente\babelente.py", line 70, in resolveoffset
    raise ValueError("Resolved offset does not match text " + str(offset) + "; minoffset=" + str(minoffset) + ", maxoffset=" + str(maxoffset) + ", lines=" + str(len(offsetmap)) )
ValueError: Resolved offset does not match text 15; minoffset=0, maxoffset=51, lines=5

Attached is a file which causes this error. Replacing double newlines with single ones resolves the issue.

[testtxt.txt](https://github.com/proycon/babelente/files/1670149/testtxt.txt)

Regards,

Marc

**Comment by proycon** [comment]
The input format is indeed one *sentence* per line, so empty lines are not supported currently. I suppose we should make this a bit more explicit in the README so you don't run into that cryptic ValueError.

**Comment by mgraauw** [comment]
OK, I can remove lines before submitting in my own script - some documentation might be good indeed. I may try converting to Folia before submitting anyway, not sure yet. Thanks for the fix + feedback!
